//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstagramApplication.CInstaSR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://schemas.datacontract.org/2004/07/InstagramReplicaService")]
    [System.SerializableAttribute()]
    public partial class Comment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int commentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creation_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int postIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int commentId {
            get {
                return this.commentIdField;
            }
            set {
                if ((this.commentIdField.Equals(value) != true)) {
                    this.commentIdField = value;
                    this.RaisePropertyChanged("commentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creation_date {
            get {
                return this.creation_dateField;
            }
            set {
                if ((this.creation_dateField.Equals(value) != true)) {
                    this.creation_dateField = value;
                    this.RaisePropertyChanged("creation_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int postId {
            get {
                return this.postIdField;
            }
            set {
                if ((this.postIdField.Equals(value) != true)) {
                    this.postIdField = value;
                    this.RaisePropertyChanged("postId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CInstaSR.IcommentService")]
    public interface IcommentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IcommentService/createComment", ReplyAction="http://tempuri.org/IcommentService/createCommentResponse")]
        void createComment(InstagramApplication.CInstaSR.Comment comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IcommentService/createComment", ReplyAction="http://tempuri.org/IcommentService/createCommentResponse")]
        System.Threading.Tasks.Task createCommentAsync(InstagramApplication.CInstaSR.Comment comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IcommentService/deleteComment", ReplyAction="http://tempuri.org/IcommentService/deleteCommentResponse")]
        void deleteComment(int commentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IcommentService/deleteComment", ReplyAction="http://tempuri.org/IcommentService/deleteCommentResponse")]
        System.Threading.Tasks.Task deleteCommentAsync(int commentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IcommentService/updateComment", ReplyAction="http://tempuri.org/IcommentService/updateCommentResponse")]
        void updateComment(InstagramApplication.CInstaSR.Comment comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IcommentService/updateComment", ReplyAction="http://tempuri.org/IcommentService/updateCommentResponse")]
        System.Threading.Tasks.Task updateCommentAsync(InstagramApplication.CInstaSR.Comment comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IcommentService/fetchComment", ReplyAction="http://tempuri.org/IcommentService/fetchCommentResponse")]
        InstagramApplication.CInstaSR.Comment[] fetchComment(int postId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IcommentService/fetchComment", ReplyAction="http://tempuri.org/IcommentService/fetchCommentResponse")]
        System.Threading.Tasks.Task<InstagramApplication.CInstaSR.Comment[]> fetchCommentAsync(int postId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IcommentServiceChannel : InstagramApplication.CInstaSR.IcommentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IcommentServiceClient : System.ServiceModel.ClientBase<InstagramApplication.CInstaSR.IcommentService>, InstagramApplication.CInstaSR.IcommentService {
        
        public IcommentServiceClient() {
        }
        
        public IcommentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IcommentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcommentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcommentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void createComment(InstagramApplication.CInstaSR.Comment comment) {
            base.Channel.createComment(comment);
        }
        
        public System.Threading.Tasks.Task createCommentAsync(InstagramApplication.CInstaSR.Comment comment) {
            return base.Channel.createCommentAsync(comment);
        }
        
        public void deleteComment(int commentId) {
            base.Channel.deleteComment(commentId);
        }
        
        public System.Threading.Tasks.Task deleteCommentAsync(int commentId) {
            return base.Channel.deleteCommentAsync(commentId);
        }
        
        public void updateComment(InstagramApplication.CInstaSR.Comment comment) {
            base.Channel.updateComment(comment);
        }
        
        public System.Threading.Tasks.Task updateCommentAsync(InstagramApplication.CInstaSR.Comment comment) {
            return base.Channel.updateCommentAsync(comment);
        }
        
        public InstagramApplication.CInstaSR.Comment[] fetchComment(int postId) {
            return base.Channel.fetchComment(postId);
        }
        
        public System.Threading.Tasks.Task<InstagramApplication.CInstaSR.Comment[]> fetchCommentAsync(int postId) {
            return base.Channel.fetchCommentAsync(postId);
        }
    }
}
